version: '2'
services:
  db:
    image: mysql/mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rd
      MYSQL_PASSWORD: p@ssw0rd
      MYSQL_USER: root
      MYSQL_DATABASE: etouch_dashboard
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - ./src/db/Dump20151202.sql:/docker-entrypoint-initdb.d/schema.sql:ro
  web:
    build: .
    command: bash -c "ant deploy && catalina.sh run"
    volumes:
      - .:/usr/local/apache-tomcat-7.0.73/webapps/etaap/
    ports:
      - "8080:8080"
    depends_on:
      - db